[package]
name = "edifact_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "edifact_parser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
